services:
  db:
    image: postgres:18
    container_name: iteh-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: iteh_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iteh_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: iteh-app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/iteh_db
      JWT_SECRET: nekiSuperTajniString123
    command: sh -c "npx prisma migrate deploy && npm run build && npm start"

volumes:
  postgres_data: